/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

/**
 *
 * @author Vedant
 */
public class BillPage extends javax.swing.JFrame {

    /**
     * Creates new form BillPage
     */
    public BillPage() {
        initComponents();
        setLocationRelativeTo(null);
        String s = "<HTML><u>PRINT BILL</u></HTML>";
        PrintBill.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fbname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        custid = new javax.swing.JLabel();
        emailid = new javax.swing.JLabel();
        altcphoneno = new javax.swing.JLabel();
        roomno = new javax.swing.JLabel();
        roomtype = new javax.swing.JLabel();
        indate = new javax.swing.JLabel();
        outdate = new javax.swing.JLabel();
        billnumber = new javax.swing.JLabel();
        dateofbooking = new javax.swing.JLabel();
        billamt = new javax.swing.JLabel();
        pymtmethod = new javax.swing.JLabel();
        cphoneno = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        PrintBill = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        purposeofstay = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        noc = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        noa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));

        jPanel1.setBackground(new java.awt.Color(201, 240, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("FINAL BILL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 110, -1));

        fbname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(fbname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 300, 20));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("CUSTOMER ID: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("NAME: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("PHONE NUMBER: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("PURPOSE OF STAY:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("PERSONAL DETAILS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel7.setText("------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 745, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setText("ROOM DETAILS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel9.setText("------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 293, 745, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("ROOM NUMBER:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setText("ROOM TYPE:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setText("NO. OF CHILDREN:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setText("CHECK-OUT DATE:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setText("BILL DETAILS");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel15.setText("------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 745, -1));

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel16.setText("BILL NUMBER:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel17.setText("DATE OF BOOKING:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel18.setText("TOTAL AMOUNT:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jLabel30.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel30.setText("THANK YOU!");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 608, -1, -1));

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel31.setText("PAYMENT METHOD: ");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        custid.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(custid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 120, 20));

        emailid.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(emailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 310, 20));

        altcphoneno.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(altcphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 160, 20));

        roomno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(roomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 303, 150, 30));

        roomtype.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(roomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 150, 20));

        indate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(indate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 130, 20));

        outdate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(outdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 130, 20));

        billnumber.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(billnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 170, 20));

        dateofbooking.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(dateofbooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 300, 20));

        billamt.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(billamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 150, 20));

        pymtmethod.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(pymtmethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 270, 30));

        cphoneno.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(cphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 80, 20));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel19.setText("/");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 10, 20));

        PrintBill.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        PrintBill.setText("PRINT BILL");
        PrintBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PrintBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrintBillMouseClicked(evt);
            }
        });
        jPanel1.add(PrintBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 70, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\billimage_60x60.png")); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 60, 60));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel21.setText("EMAIL ID:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        purposeofstay.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(purposeofstay, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 180, 20));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel22.setText("LogOut");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, 70, 30));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 80, 20));

        noc.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(noc, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 80, 30));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel24.setText("NO. OF ADULTS:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel25.setText("CHECK-IN DATE:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        noa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(noa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrintBillMouseClicked
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
            
        job.setPrintable(new Printable(){
        public int print(Graphics pg,PageFormat pf, int pageNum){
            pf.setOrientation(PageFormat.LANDSCAPE);
            if(pageNum > 0){
                return Printable.NO_SUCH_PAGE;
            }
                
            Graphics2D g2 = (Graphics2D)pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            g2.scale(0.77, 1.00);
            jPanel1.print(g2);
            return Printable.PAGE_EXISTS;    
        }
    });
        
        boolean ok = job.printDialog();
        if(ok){
            try{
                job.print();
            }
        catch (PrinterException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_PrintBillMouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        OptionPage op = new OptionPage();
        op.setVisible(true);
        op.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel22MouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PrintBill;
    public javax.swing.JLabel altcphoneno;
    public javax.swing.JLabel billamt;
    public javax.swing.JLabel billnumber;
    public javax.swing.JLabel cphoneno;
    public javax.swing.JLabel custid;
    public javax.swing.JLabel dateofbooking;
    public javax.swing.JLabel emailid;
    public javax.swing.JLabel fbname;
    public javax.swing.JLabel indate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel noa;
    public javax.swing.JLabel noc;
    public javax.swing.JLabel outdate;
    public javax.swing.JLabel purposeofstay;
    public javax.swing.JLabel pymtmethod;
    public javax.swing.JLabel roomno;
    public javax.swing.JLabel roomtype;
    // End of variables declaration//GEN-END:variables
}
