
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import java.util.*;
//import java.sql;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Vedant
 */
public class CreateAccountPage extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccountPage
     */
    int customerid;
    public CreateAccountPage() {
        initComponents();
        String s = "<HTML><u>Sign in instead</u></HTML>";
        jLabel8.setText(s);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderSelector = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        CreateAccount = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        passwordconfirm = new javax.swing.JPasswordField();
        JLabelpassword = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        others = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        phoneno2 = new javax.swing.JTextField();
        phoneno1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(201, 240, 246));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateAccount.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        CreateAccount.setText("Create Your Account");
        jPanel1.add(CreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 10, -1, -1));

        fname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 80, 142, -1));
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 80, 142, -1));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 133, 142, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 56, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 56, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 109, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 222, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 174, -1));
        jPanel1.add(passwordconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 174, -1));

        JLabelpassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        JLabelpassword.setText("Confirm Password");
        jPanel1.add(JLabelpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        CreateButton.setBackground(new java.awt.Color(51, 204, 255));
        CreateButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        CreateButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateButton.setText("CREATE");
        CreateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CreateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 250, 39));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Date Of Birth");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 109, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 2, 15)); // NOI18N
        jLabel8.setText("Sign In instead");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Gender");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\userimageCA.jpg")); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 109, 180, 207));

        dob.setDateFormatString("dd-MMM-yyyy");
        dob.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 133, 142, -1));

        GenderSelector.add(male);
        male.setText("Male");
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 86, -1));

        GenderSelector.add(female);
        female.setText("Female");
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 86, -1));

        GenderSelector.add(others);
        others.setText("Others");
        jPanel1.add(others, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 86, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("Alternate Phone Number");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));
        jPanel1.add(phoneno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 142, -1));
        jPanel1.add(phoneno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 142, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setText("Phone Number");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        UserPage up = new UserPage();
        up.setVisible(true);
        up.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // TODO add your handling code here:
        Connection conn;
        PreparedStatement ps, ps1, ps2, ps3;
        ResultSet rs;
        String fname,lname,username,email,password,cphoneno,altcphoneno;
        
        fname = this.fname.getText();
        lname = this.lname.getText();
        username = this.username.getText();
        //Date dob = new Date(dob.getDate());
        //java.util.Date utilDate = new java.util.Date();
        //java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        //dob = this.dob.getDateFormatString();
        
        java.util.Date dobtemp = this.dob.getDate();
        java.sql.Date dob = new java.sql.Date(dobtemp.getTime());
        cphoneno = this.phoneno1.getText();
        altcphoneno = this.phoneno2.getText();
        email=this.email.getText();
        password = this.password.getText();
        String passwordFromDb=null;
        String passwordconfirm;
        passwordconfirm = this.passwordconfirm.getText();
        long millis = System.currentTimeMillis();  
        java.sql.Date currentdate = new java.sql.Date(millis);
        
        
        
        try
        {
            if(dob.compareTo(currentdate) > 0)
            {
                JOptionPane.showMessageDialog(this,"Date of birth is not valid");
            }
            else if(cphoneno.length() != 10 || altcphoneno.length() != 10)
            {
                JOptionPane.showMessageDialog(this,"Please enter valid phone number");
            }
            else if(username != null && password != null)
            {
                if(password.equals(passwordconfirm))
                {
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/myhotel?user=root&password=root");
                    ps = conn.prepareStatement("insert into user(fname,lname,username,dob,email,password,gender)values(?,?,?,?,?,?,?)");
                    
                    //ps.setInt(1, customerid);
                    ps.setString(1, fname);
                    ps.setString(2, lname);
                    ps.setString(3, username);
                    ps.setDate(4, dob);
                    ps.setString(5, email);
                    ps.setString(6, password);
                    if(male.isSelected())
                    {
                        ps.setString(7, "Male");
                    }
                    if(female.isSelected())
                    {
                        ps.setString(7, "Female");
                    }
                    if(others.isSelected())
                    {
                        ps.setString(7, "Others");
                    }
                    ps.executeUpdate();
                    
                    ps3 = conn.prepareStatement("select cust_id from user where username = ?");
                    ps3.setString(1, username);
                    rs = ps3.executeQuery();
                    while(rs.next())
                    {
                        customerid = rs.getInt("cust_id");
                    }
                   
                        
                    
                    
                    ps1 = conn.prepareStatement("insert into cphoneno values(?, ?)");
                    ps1.setInt(1, customerid);
                    ps1.setString(2, cphoneno);
                    ps2 = conn.prepareStatement("insert into cphoneno values(?, ?)");
                    ps2.setInt(1, customerid);
                    ps2.setString(2, altcphoneno);
                    
                    
                    
                    //ps.executeQuery();
                    
                    ps1.executeUpdate();
                    ps2.executeUpdate();
                    //ps1.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Account Created Successfully!");
                    UserPage up = new UserPage();
                    up.setVisible(true);
                    up.setLocationRelativeTo(null);
                    this.dispose();
                    
                    
                    
                }
                
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_CreateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreateAccount;
    private javax.swing.JButton CreateButton;
    private javax.swing.ButtonGroup GenderSelector;
    private javax.swing.JLabel JLabelpassword;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton others;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField passwordconfirm;
    private javax.swing.JTextField phoneno1;
    private javax.swing.JTextField phoneno2;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
