/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

/**
 *
 * @author Vedant
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        setLocationRelativeTo(null);
        hcustid.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserMenu = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogOutLabel = new javax.swing.JLabel();
        unfromlogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BookMyStayBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        hcustid = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        UserMenu.setText("User");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(201, 240, 246));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(201, 240, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        jLabel1.setText("Welcome, ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 70));

        LogOutLabel.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        LogOutLabel.setText("LogOut");
        LogOutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutLabelMouseClicked(evt);
            }
        });
        jPanel1.add(LogOutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, -1));

        unfromlogin.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        jPanel1.add(unfromlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 233, 70));

        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 0, 66, 59));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\deluxeroom_2_160x150.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 160, 150));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\simpleroom_160x150.jpg")); // NOI18N
        jLabel5.setText("jLabel4");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 160, 150));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\Suiteroom_4_160x150.jpg")); // NOI18N
        jLabel6.setText("jLabel4");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 160, 150));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel7.setText("Simple");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel8.setText("Suite");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel9.setText("Deluxe");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        BookMyStayBTN.setBackground(new java.awt.Color(5, 56, 107));
        BookMyStayBTN.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        BookMyStayBTN.setForeground(new java.awt.Color(237, 245, 225));
        BookMyStayBTN.setText("BOOK MY STAY");
        BookMyStayBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BookMyStayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookMyStayBTNActionPerformed(evt);
            }
        });
        jPanel1.add(BookMyStayBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 260, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\noofguest_20x20.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 20, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\bedlogo_1_20x20.jpg")); // NOI18N
        jLabel10.setText("jLabel3");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 20, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\bedlogo_1_20x20.jpg")); // NOI18N
        jLabel11.setText("jLabel3");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 20, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\wifilogo_20x20.png")); // NOI18N
        jLabel12.setText("jLabel3");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 20, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\jacuzzilogo_20x20.jpg")); // NOI18N
        jLabel14.setText("jLabel3");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 20, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\bedlogo_1_20x20.jpg")); // NOI18N
        jLabel15.setText("jLabel3");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 20, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\noofguest_20x20.jpg")); // NOI18N
        jLabel16.setText("jLabel3");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 20, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\noofguest_20x20.jpg")); // NOI18N
        jLabel17.setText("jLabel3");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 20, 20));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel18.setText("King Size Bed ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, -1));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel19.setText("King Size Bed ");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel20.setText("King Size Bed ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel21.setText("Upto 3 guests");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel22.setText("Upto 2 guests");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel23.setText("Upto 3 guests");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 90, 20));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel24.setText("Jaccuzzi");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 60, 20));

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\wifilogo_20x20.png")); // NOI18N
        jLabel25.setText("jLabel3");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 20, 20));

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel26.setText("Complimentary Wifi");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel27.setText("Complimentary Wifi");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));
        jPanel1.add(hcustid, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 580, 40, 10));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setText("Rs.4000/day");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 120, 50));

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel28.setText("Rs.7000/day");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 120, 50));

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel29.setText("Rs.2500/day");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutLabelMouseClicked
        // TODO add your handling code here:
        OptionPage op = new OptionPage();
        op.setVisible(true);
        op.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_LogOutLabelMouseClicked

    private void BookMyStayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookMyStayBTNActionPerformed
        // TODO add your handling code here:
        BookStay bs = new BookStay();
        bs.bashcustid.setText(hcustid.getText());
        //System.out.println(bashcustid);
        bs.setVisible(true);
        bs.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_BookMyStayBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookMyStayBTN;
    private javax.swing.JLabel LogOutLabel;
    private javax.swing.JMenu UserMenu;
    public javax.swing.JLabel hcustid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel unfromlogin;
    // End of variables declaration//GEN-END:variables
}
