/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import java.util.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Vedant
 */
public class NecessaryDetailsPage extends javax.swing.JFrame {

    /**
     * Creates new form NecessaryDetailsPage
     */
    long millis = System.currentTimeMillis();  
    java.sql.Date currentdate = new java.sql.Date(millis);
    public NecessaryDetailsPage() {
        initComponents();
        setLocationRelativeTo(null);
        ndphcustid.setVisible(false);
        ndpfinalrooomno.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aadharno = new javax.swing.JTextField();
        ProceedBTN = new javax.swing.JButton();
        ndphcustid = new javax.swing.JLabel();
        ndpfinalrooomno = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CreditCard = new javax.swing.JRadioButton();
        DebitCard = new javax.swing.JRadioButton();
        GpayPaytm = new javax.swing.JRadioButton();
        NetBanking = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        PayAtHotel = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        amt = new javax.swing.JLabel();
        finalamt = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        gst = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(201, 240, 246));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Fill in the necessary details");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Aadhar Number");

        ProceedBTN.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ProceedBTN.setText("PROCEED");
        ProceedBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProceedBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedBTNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Payment Methods");

        buttonGroup1.add(CreditCard);
        CreditCard.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        CreditCard.setText("Credit Card");

        buttonGroup1.add(DebitCard);
        DebitCard.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        DebitCard.setText("Debit Card");

        buttonGroup1.add(GpayPaytm);
        GpayPaytm.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        GpayPaytm.setText("Gpay/Paytm");

        buttonGroup1.add(NetBanking);
        NetBanking.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        NetBanking.setText("NetBanking");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Price");

        buttonGroup1.add(PayAtHotel);
        PayAtHotel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        PayAtHotel.setText("Pay At Hotel");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\My_project_14x22.png")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setText("Total");

        amt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        finalamt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setText("Taxes");

        gst.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel14.setText("-----------------------------------------------------------------------------------");

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\My_project_14x22.png")); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Business" }));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Purpose Of Stay");

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\My_project_14x22.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vedant\\Downloads\\My project (1).png")); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jComboBox3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("No. of Adults");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setText("No. of Children");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ndpfinalrooomno, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finalamt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreditCard)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gst, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NetBanking)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(DebitCard)))))
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aadharno, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(PayAtHotel)
                            .addComponent(GpayPaytm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(93, 93, 93))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ndphcustid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProceedBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aadharno)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreditCard)
                            .addComponent(DebitCard))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GpayPaytm)
                            .addComponent(NetBanking, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(PayAtHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gst, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalamt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProceedBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ndphcustid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(ndpfinalrooomno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProceedBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedBTNActionPerformed
        // TODO add your handling code here:
        
        BillPage bp = new BillPage();
        int finaluseramt = 0, price, total_days;
        bp.custid.setText(ndphcustid.getText());
        Connection conn;
        PreparedStatement ps, ps1, ps2, ps3, ps4, ps5;
        ResultSet rs, rs1, rs2, rs3, rs4, rs5;
        DateFormat df1 = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss"); 
        bp.dateofbooking.setText(String.valueOf(sdf.format(currentdate)));
        
        if(buttonGroup1.getSelection() == null)
        {
            JOptionPane.showMessageDialog(this,"Please select a valid payment method");
        }
        
        else if(aadharno == null || aadharno.getText().length() < 12)
        {
            JOptionPane.showMessageDialog(this,"Please enter valid aadhar number");
        }
        
        else
        {
            
            
            try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/myhotel?user=root&password=root");
            ps = conn.prepareStatement("select fname,lname,email from user where cust_id = ?");
            ps.setString(1, ndphcustid.getText());
            rs = ps.executeQuery();
            
            while(rs.next())
            {
                bp.fbname.setText(rs.getString("fname") + " " + rs.getString("lname"));
                bp.emailid.setText(rs.getString("email"));
            }
            
            
            ps1 = conn.prepareStatement("select all phoneno from cphoneno where cust_id = ?");
            ps1.setString(1, ndphcustid.getText());
            rs1 = ps1.executeQuery();
            
            ArrayList<Long> phoneNo = new ArrayList<Long>();
            while(rs1.next())
            {
                long result = rs1.getLong(1);
                phoneNo.add(result);
            }
            
            bp.cphoneno.setText(String.valueOf(phoneNo.get(0)));
            bp.altcphoneno.setText(String.valueOf(phoneNo.get(1)));
            ps2 = conn.prepareStatement("select rtype, price, indate, outdate, totaldays from room where rno = ?");
            ps2.setString(1, ndpfinalrooomno.getText());
            rs2 = ps2.executeQuery();
            
            while(rs2.next())
            {
                bp.roomno.setText(ndpfinalrooomno.getText());
                bp.roomtype.setText(rs2.getString("rtype"));
                java.sql.Date sqlindate = rs2.getDate("indate");
                java.util.Date tempindate = new java.util.Date(sqlindate.getTime());
                String finalindate = df1.format(tempindate);
                
                java.sql.Date sqloutdate = rs2.getDate("outdate");
                java.util.Date tempoutdate = new java.util.Date(sqloutdate.getTime());
                String finaloutdate = df1.format(tempoutdate);
                bp.indate.setText(String.valueOf(finalindate));
                bp.outdate.setText(String.valueOf(finaloutdate));
                //bp.indate.setText(String.valueOf((rs2.getDate("indate"))));
                //bp.outdate.setText(String.valueOf(rs2.getDate("outdate")));
                price = rs2.getInt("price");
                total_days = rs2.getInt("totaldays");
                finaluseramt = price * total_days;
                
            }
            
            
            ps3 = conn.prepareStatement("insert into bill(amount,date,paymentmethod,cust_id) values (?,?,?,?)") ;
            ps3.setString(1, String.valueOf(finaluseramt));
            ps3.setDate(2, currentdate);
            ps3.setString(4, ndphcustid.getText());
            
            if(CreditCard.isSelected())
            {
                ps3.setString(3, "Credit Card");
                bp.pymtmethod.setText("Credit Card");
            }
            if(DebitCard.isSelected())
            {
                ps3.setString(3, "Debit Card");
                bp.pymtmethod.setText("Debit Card");
            }
            if(GpayPaytm.isSelected())
            {
                ps3.setString(3, "Gpay/Paytm");
                bp.pymtmethod.setText("Gpay/Paytm");
            }
            if(NetBanking.isSelected())
            {
                ps3.setString(3, "NetBanking");
                bp.pymtmethod.setText("NetBanking");
            }
            if(PayAtHotel.isSelected())
            {
                ps3.setString(3, "Pay At Hotel");
                bp.pymtmethod.setText("Paying At Hotel");
            }
            ps3.executeUpdate();
            
            ps4 = conn.prepareStatement("update user set aadharno = ? where cust_id = ?");
            ps4.setString(1, String.valueOf(aadharno.getText()));
            ps4.setString(2, ndphcustid.getText());
            ps4.executeUpdate();
            
            ps5 = conn.prepareStatement("select billno, amountaftergst from bill ORDER BY billno DESC LIMIT 1");
            rs5 = ps5.executeQuery();
            
            while(rs5.next())
            {
                bp.billnumber.setText(String.valueOf(rs5.getInt("billno")));
                bp.billamt.setText("Rs." + String.valueOf(rs5.getFloat("amountaftergst")));
            }
            
            String purpose = String.valueOf(jComboBox1.getSelectedItem().toString());
            if(purpose == "Personal")
            {
                bp.purposeofstay.setText("PERSONAL");
            }
            if(purpose == "Business")
            {
                bp.purposeofstay.setText("BUSINESS");
            }
            
            
            String noa = String.valueOf(jComboBox2.getSelectedItem().toString());
            if(noa == "1")
            {
                bp.noa.setText("1");
            }
            if(noa == "2")
            {
                bp.noa.setText("2");
            }
            if(noa == "3")
            {
                bp.noa.setText("3");
            }
            if(noa == "4")
            {
                bp.noa.setText("4");
            }
            
            String noc = String.valueOf(jComboBox3.getSelectedItem().toString());
            if(noc == "0")
            {
                bp.noc.setText("0");
            }
            if(noc == "1")
            {
                bp.noc.setText("1");
            }
            if(noc == "2")
            {
                bp.noc.setText("2");
            }
           
            
            bp.setVisible(true);
            bp.setLocationRelativeTo(null);
            this.dispose();
        }
            catch(Exception e)
        {
            System.out.println(e);
        }
      }
        
        
    }//GEN-LAST:event_ProceedBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NecessaryDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NecessaryDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NecessaryDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NecessaryDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NecessaryDetailsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CreditCard;
    private javax.swing.JRadioButton DebitCard;
    private javax.swing.JRadioButton GpayPaytm;
    private javax.swing.JRadioButton NetBanking;
    private javax.swing.JRadioButton PayAtHotel;
    private javax.swing.JButton ProceedBTN;
    private javax.swing.JTextField aadharno;
    public javax.swing.JLabel amt;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel finalamt;
    public javax.swing.JLabel gst;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel ndpfinalrooomno;
    public javax.swing.JLabel ndphcustid;
    // End of variables declaration//GEN-END:variables
}
